name: My First Workflow TODO

# trigger
on:
  push:
    branches:
    - "release/.+"

# Jobs in the workflow
jobs:
  #job name,
  TODO-workflow:
    # OS that this workflow will be running on
    runs-on: ubuntu-latest

    # list of steps to perform task
    steps:
    - name: Echo the branch name
      run: echo "Current branch - ${{ github.ref_name }}"
    - name: Checkout the current repo
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref_name }}