name: My First Workflow TODO

# trigger
on:
  push:
    branches:
    - "release/*"

# Jobs in the workflow
jobs:
  #job name,
  TODO-workflow:
    # OS that this workflow will be running on
    runs-on: ubuntu-latest

    # list of steps to perform task
    steps:
    - name: Echo the branch name
      run: echo "Current branch - ${{ github.ref_name }}"
    - name: Checkout the current repo
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref_name }}
    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v25.1.0
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        github-token: ${{ secrets.GHTOKEN }}
        vercel-org-id: ${{ secrets.ORGID }}
        vercel-project-id: ${{ secrets.PROJECTID }}