name: My First Workflow TODO

# trigger
on:
  push:
    branches:
    - "release/*"

# Jobs in the workflow
jobs:
  #job name,
  TODO-workflow:
    # OS that this workflow will be running on
    runs-on: ubuntu-latest

    # list of steps to perform task
    steps:
    - name: Checkout the current repo
      uses: actions/checkout@v3
    